internet_host:
    ip: 192.168.0.8
    ssh_port: 22
    user: "sdn"
    passwd: "Fw1NLLbliTR0q11y7VjBnBHIUhZYZb7e"
    key: "/var/lib/jenkins/.ssh/sdn_rsa"
cloud:
    bucketName: 'netskyper-obs-bucket'
    objName: 'netskyper-obs-objname.qcow2'
    localImagePath: '/home/sdn/netskyper-cpe.qcow2'
    imageName: 'netskyper-image'
    sGroupName: 'netskyper-sgroup'
    vpcName: 'netskyper-vpc'
    wanNetName: 'netskyper-wan'
    lanNetName: 'netskyper-lan'
    serverName: "test-netskyper-server"
    floating_network_id: "0a2228f2-7f8a-45f1-8e09-9039e1d09975"
hw_cloud:
    projectId: '0874d4cbc28025262f1bc0074dba0d0a'
    AK: "PJTRMYFEBKHNBA0KRM92"
    SK: "sSRyEw70oactmcOy8Tg6LiaCTtkpd3PrPd02GBKt"
    cloud: 'myhuaweicloud.com'
    region: 'cn-east-3'
    bucketServer: 'https://obs.cn-east-3.myhuaweicloud.com'
    availability_zone: 'cn-east-3a'
    flavorType: "s6.small.1"
    pcImageId: 'ff61492a-64fd-4783-bfc6-b7db0543ce70'
    pcName: "hw_host"
    vpcCIDR: '172.16.0.0/16'
    wanCIDR: '172.16.1.0/24'
    wangw: '172.16.1.1'
    lanCIDR: '172.16.2.0/24'
    langw: '172.16.2.1'
ali_cloud:
    AK: "LTAI4GDQRYHUaJX1dK7yZ3Uv"
    SK: "p3OM4sMKOitBVJZj2gwwQDUCCPWfXt"
    region: 'cn-shanghai'
    availability_zone: 'cn-shanghai-b'
    flavorType: "ecs.t5-lc1m1.small"
    pcName: "ali_pc"
    pcImageId: 'ubuntu_18_04_x64_20G_alibase_20200817.vhd'
    vpcCIDR: '172.17.0.0/16'
    wanCIDR: '172.17.1.0/24'
    wangw: '172.17.1.1'
    lanCIDR: '172.17.2.0/24'
    langw: '172.17.2.1'
azure_cloud:
    AZURE_CLIENT_ID: '37e0b886-5df0-4cf6-ba44-71343bbffd82'
    AZURE_SUBSCRIPTION_ID: "11fbc75d-96a0-40d5-803e-4aaef769f9a6"
    AZURE_TENANT_ID: "cd6a4204-b6b5-4c80-8411-5281749b15a3"
    AZURE_CLIENT_SECRET: 'mv49uMT5ZT1FPAu__jmB-bFQ-FuXv_2X7Z'
    resourceGrpName: "netskyperRes"
    location: 'chinanorth2'
    pubIpName: 'netskyper-pubIp'
    wanNicName: 'netskyper-wanNic'
    lanNicName: 'netskyper-lanNic'
    imageDisk_id: "/subscriptions/11fbc75d-96a0-40d5-803e-4aaef769f9a6/resourceGroups/netskyperRes/providers/Microsoft.Compute/disks/netskyperDisk"
    flavorType: 'Standard_B1s'
    imageDiskName: 'netskyperDisk'
    vhdFilePath: '/home/sdn/netskyper-cpe_azure.vhd'
    azcopyToolPath: '/home/sdn/aohang/azcopy_linux_amd64_10.6.0/azcopy'
    hostName: 'azurehost'
    hostUser: 'azure_user'
    hostPwd: 'Passw0rd'
    hostLanName: 'azure_lan'
    hostsize: 'Standard_B1s'
    vpcCIDR: '172.18.0.0/16'
    wanCIDR: '172.18.1.0/24'
    wangw: '172.18.1.1'
    lanCIDR: '172.18.2.0/24'
    langw: '172.18.2.1'
aws_cloud:
    key_path: "/home/sdn/aiwan_aws.pem"
    image_path: "/home/sdn/openwrt/images/netskyper-cpe-rootfs-ext4.img"
    image_name: "netskyper-cpe-rootfs-ext4.img"
    image_server_name: "Image_server"
    image_size: "t2.micro"
    image_server_id: "ami-0071f6f4df15863cc"
    vcpe_size: "t1.micro"
    vpcCIDR: '172.19.0.0/16'
    wanCIDR: '172.19.1.0/24'
    wangw: '172.19.1.1'
    lanCIDR: '172.19.2.0/24'
    langw: '172.19.2.1'
